### ISSUE TITLE
hoe function doesn't work

### ISSUE THREAD

**Issue by CyberSteve777** [AmyMialeeMods/piercing-paxels#1]
mc version: 1.19.2
mod version: 1.0.1

https://user-images.githubusercontent.com/69720241/184209631-b34d3f7d-e68f-43d3-a41e-0a720dd5cd59.mp4

**Comment by AmyMialee** [comment]
Do you have the Hoe Upgrade?

**Comment by CyberSteve777** [comment]
oh, looks like no, it should be?

**Comment by CyberSteve777** [comment]
Didn't find UI previously. Closing
