### ISSUE TITLE
[1.18.2] Crash when mining a mechanical piston from create

### ISSUE THREAD

**Issue by Ellemes** [AmyMialeeMods/piercing-paxels#3]
https://github.com/AmyMialeeMods/piercing-paxels/blob/039886cd3f40d500dca69939e8fdcefdbfe35d96/src/main/java/amymialee/piercingpaxels/mixin/BlockMixin.java#L36
player was null causing a NPE, not sure why it was null but might be worth doing nothing if it is.
[crash-2022-08-30_17.51.39-server.txt](https://github.com/AmyMialeeMods/piercing-paxels/files/9455447/crash-2022-08-30_17.51.39-server.txt)

**Comment by AmyMialee** [comment]
i suppose 1.18.2 might be getting another update then, thanks
