### ISSUE TITLE
[Feature Request] Efficiency affects Digging Upgrades

### ISSUE THREAD

**Issue by mmmmmabil** [AmyMialeeMods/piercing-paxels#4]
i find it weird that when using the digging upgrades the material the tool is made of as well as the level of efficiency does not affect the speed at which blocks break
would it be possible to make it scale up depending on the tool or maybe even rework it entierly in the future
perhaps having a hotkey to toggle the 'special' digging mode so u make use of them better for example with haste and eff5

**Comment by AmyMialee** [comment]
i might change up the upgrades a bit, and this is a good idea for it, thanks

**Comment by AmyMialee** [comment]
it's very difficult to get information about the player in the usage method, so efficiency will work but haste will not.
