### ISSUE TITLE
piercingpaxels-1.0.12 include Obsidian?

### ISSUE THREAD

**Issue by VsUK** [AmyMialeeMods/piercing-paxels#42]
I was wondering if when you have time, to add ObsidianPaxel to the mod & possible have the mod generate a config file for changing the paxel's health. I know you said the smelting upgrade & so on doesn't work & you won't update until the next big update for mc, but I don't think this would take you more than 5 or 10 minutes. I'd do it myself, but there's no easy way to decompile & edit the class files, unless adding is done by .json files I've found. 

Would appreciate it a lot if you could. 

Thanks again :)

**Comment by AmyMialee** [comment]
Is Obsidian Tools another mod or something?

**Comment by VsUK** [comment]
No, I was asking if you could add Obsidian Paxel to your existing tools in the piercingpaxels mod for 1.20.1 forge. It has netherite but not obsidian with the tools health being changeable via a config if possible.

**Comment by AmyMialee** [comment]
I'd rather not have custom standalone paxels, too confusing for balance.

**Comment by VsUK** [comment]
It's not a standalone paxel, it's simply adding Obsidian to the current mod. You have diamonds & then it jumps to netherite, skipping obsidian. The health simply has to be somewhere in between diamonds & netherite.

**Comment by AmyMialee** [comment]
uh there is no such thing as obsidian tools
