### ISSUE TITLE
[Feature Request] Add Variants Copper, Ruby, Saphire and Peridot

### ISSUE THREAD

**Issue by sayore** [AmyMialeeMods/piercing-paxels#6]
Mostly taken inspiration of Tech Reborn, it would be kinda neat to have these as Paxel options too.

**Comment by AmyMialee** [comment]
As in doing Tech Reborn compatibility specifically?
Or just doing generic copper/ruby/sapphire/peridot paxels (and then needing the gemstone items too)?

**Comment by AmyMialee** [comment]
I can add paxels for any mod really, especially ones that have their mod hosted on a maven, all it takes is making the texture and registering the item.

**Comment by sayore** [comment]
Tech Reborn specifically would be appreciated by me and others, i dont really know anyother mods really that include them(the gems i mean) 🤔
Copper would probably benefit from a generall addition if there is a pickaxe/other tools which are made from copper in the game.

**Comment by sayore** [comment]
If you want me to, i could spin up the required textures for you from the color palettes of the gem pickaxes

**Comment by AmyMialee** [comment]
> If you want me to, i could spin up the required textures for you from the color palettes of the gem pickaxes

I prefer to do custom textures where possible, especially where the original mod has unique textures on it's tools.
I didn't do copper since TR has no copper tools, but it does have Bronze.
And I added some electric Dracks (**Dr**ill Ch**a**insaw Ja**ck**hammer) that function the same but use TR energy.

**Comment by AmyMialee** [comment]
Make another issue if you still want the copper paxel, but be sure to mention a mod to add it as compat for, since I don't really want to have copper tools as a feature of a paxel mod.

**Comment by sayore** [comment]
Nononoonono its fine i like this, copper is kinda meh anyway, would just have been a nice extra i guess. The Copper tools are from Indrev in AoF but there is no maven, and tbf the gem tools are golden by itself anyway; and holy smokes did you add the Dracks fast good job on that!
